echo db_name = orcl > orc1.ora
echo db_files = 1020 >> orc1.ora
echo control_files = ("%ORA_PATH%\database\ctl1orcl.ora", "%ORA_PATH%\database\ctl2orcl.ora") >> orc1.ora
echo db_file_multiblock_read_count = 16 >> orc1.ora 
echo db_block_buffers = 550 >> orc1.ora
echo shared_pool_size = 9000000 >> orc1.ora
echo log_checkpoint_interval = 8000 >> orc1.ora
echo processes = 60 >> orc1.ora
echo dml_locks = 200 >> orc1.ora
echo log_buffer = 32768 >> orc1.ora
echo sequence_cache_entries = 30 >> orc1.ora
echo sequence_cache_hash_buckets = 23 >> orc1.ora
echo #audit_trail = true >> orc1.ora
echo #timed_statistics = true >> orc1.ora
echo background_dump_dest = %ORA_PATH%\rdbms80\trace >> orc1.ora
echo user_dump_dest = %ORA_PATH%\rdbms80\trace >> orc1.ora
echo db_block_size =8192 >> orc1.ora
echo compatible = 8.0.5.0.0 >> orc1.ora
echo sort_area_size = 20000000 >> orc1.ora
echo log_checkpoint_timeout = 0 >> orc1.ora
echo remote_login_passwordfile = shared >> orc1.ora
echo max_dump_file_size = 10240 >> orc1.ora
echo max_enabled_roles=50 >> orc1.ora
echo open_cursors=100 >> orc1.ora
