spool E:\orant\database\spoolmain
set echo on
connect INTERNAL/sys
ALTER DATABASE DATAFILE 'E:\orant\database\Sys1orcl.ora' AUTOEXTEND ON;
CREATE ROLLBACK SEGMENT SYSROL TABLESPACE "SYSTEM" STORAGE (INITIAL 100K NEXT 100K);
ALTER ROLLBACK SEGMENT "SYSROL" ONLINE;
@E:\orant\Rdbms80\admin\catalog.sql;
@E:\orant\Rdbms80\admin\catproc.sql
@E:\orant\Rdbms80\admin\caths.sql

REM **************TABLESPACE FOR ROLLBACK*****************
CREATE TABLESPACE ROLLBACK_DATA DATAFILE 'E:\orant\database\Rbs1orcl.ora' SIZE 50M
DEFAULT STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 2 MAXEXTENTS 121 PCTINCREASE 0);
ALTER DATABASE DATAFILE 'E:\orant\database\Rbs1orcl.ora' AUTOEXTEND ON;

REM ***********Alter system tablespace ********************
ALTER TABLESPACE SYSTEM
DEFAULT STORAGE ( INITIAL 100K NEXT 100K MINEXTENTS 1 MAXEXTENTS 300 PCTINCREASE 1);

REM **************TABLESPACE FOR USER*********************
CREATE TABLESPACE USER_DATA DATAFILE 'E:\orant\database\Usr1orcl.ora' SIZE 500M
DEFAULT STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 1);
ALTER DATABASE DATAFILE 'E:\orant\database\Usr1orcl.ora' AUTOEXTEND ON;

REM **************TABLESPACE FOR TEMPORARY*****************
CREATE TABLESPACE TEMPORARY DATAFILE 'E:\orant\database\Tmp1orcl.ora' SIZE 20M
DEFAULT STORAGE ( INITIAL 100K NEXT 100K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 0) TEMPORARY;
ALTER DATABASE DATAFILE 'E:\orant\database\Tmp1orcl.ora' AUTOEXTEND ON;

REM **************TABLESPACE FOR INDEX*********************
CREATE TABLESPACE INDX DATAFILE 'E:\orant\database\Indx1orcl.ora' SIZE 10M
DEFAULT STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 1);
ALTER DATABASE DATAFILE 'E:\orant\database\Indx1orcl.ora' AUTOEXTEND ON;

REM **** Creating two rollback segments ****************
CREATE PUBLIC ROLLBACK SEGMENT RB0 TABLESPACE "ROLLBACK_DATA"
STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 2 MAXEXTENTS 121 );
CREATE PUBLIC ROLLBACK SEGMENT RB1 TABLESPACE "ROLLBACK_DATA"
STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 2 MAXEXTENTS 121 );
ALTER ROLLBACK SEGMENT "RB0" ONLINE;
ALTER ROLLBACK SEGMENT "RB1" ONLINE;
alter user sys temporary tablespace TEMPORARY;
alter user system default tablespace USER_DATA;
alter rollback segment "SYSROL" offline;
spool off
