/*****				  scrneng.c				*****/

char	okbutton[]=    	"    OK    " ,
	cancelbutton[]=	"  Cancel  " ,
	exitbutton[]=  	"   Exit   " ,
	yesbutton[]=    "   Yes    " ,
	nobutton[]=	"    No    " ,

	outofmem[]="Out of memory" ,
	cantopenmes[]="Can't open" ,
	printtomes[]="Print to:" ,
	prnnotreadymes[]="Printer not ready" ,
	savefilemes[]="Save file before exiting?" ,
	printingmes[]="Printing... Press 'esc' to stop." ,
	linedrawmes[]="Linedraw. Arrows - cursor movement , alt+arrows - drawing,esc-exit" ,
	openfiletitle[]=" Open File " ,
	filetoobigmes[]="File is too big" ;
