/* Удаление всех таблиц (в нормальной работе не применяется) */

drop table tovary ;
drop table tmp_sums ;
drop TABLE UDBOPT ;
drop table anal_errs ;
drop table privtest;
drop table objpriv;
DROP table DBCATTREE;
DROP TABLE DBCAT;
DROP TABLE DBADDINFO;
DROP TABLE DBOPTOV;
DROP TABLE DBOPT;
DROP TABLE dbhistory ;
DROP TABLE history ;
DROP TABLE unapp_items ;
DROP TABLE unapp_cor_items ;
DROP TABLE unapp_opers ;
DROP TABLE cor_items ;
DROP TABLE op_items ;
DROP TABLE del_op_items ;
DROP TABLE del_opers ;
DROP TABLE opers ;
DROP TABLE cond_items ;
DROP TABLE conds ;
DROP TABLE consts ;
DROP TABLE cattree ;
DROP TABLE cor_turns ;
DROP TABLE turns ;
DROP TABLE rems ;
DROP TABLE sums ;
DROP TABLE user_options ;
DROP TABLE cints ;
DROP TABLE cps ;
DROP TABLE ex_accs ;
DROP TABLE accs ;
DROP TABLE DBSTR;
DROP TABLE objs;
DROP TABLE objcat;
DROP SEQUENCE SumSeq ;
DROP SEQUENCE OperSeq ;
DROP SEQUENCE ObjSeq ;
DROP SEQUENCE TreeSeq ;
DROP SEQUENCE DBCatSeq ;

exit
